Refactor workflows

diff --git a/.github/workflows/webgl_build.yml b/.github/workflows/webgl_build.yml
--- a/.github/workflows/webgl_build.yml
+++ b/.github/workflows/webgl_build.yml
@@ -37,7 +37,7 @@ jobs:
 
           if [ -z "${{ vars.PROJECT_NAME }}" ]; then
             echo "Error: PROJECT_NAME variable is not set ❌."
-            echo "PROJECT_NAME=defaultUnityProject" >> $GITHUB_ENV
+            echo "PROJECT_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV
             echo "Setting PROJECT_NAME to ${{ vars.PROJECT_NAME }}"
           fi
 
@@ -60,14 +60,11 @@ jobs:
           swap-storage: true
 
   build:
-    name: Build ${{ matrix.targetPlatform }}
+    name: Build WebGL
     runs-on: ubuntu-latest
     needs: free-disk-space
     strategy:
       fail-fast: false
-      matrix:
-        targetPlatform:
-          - WebGL
     steps:
       - name: Set current date as env variable
         run: echo "START_TIME=$(date -u +%s)" >> $GITHUB_ENV
@@ -82,7 +79,7 @@ jobs:
           path: |
             Library
             Temp
-          key: Library-${{ matrix.targetPlatform }}
+          key: Library-WebGL
 
       - name: Clean /tmp and /opt
         run: |
@@ -96,7 +93,7 @@ jobs:
         
 
       # Build
-      - name: Create the WebGL build
+      - name: Build
         uses: game-ci/unity-builder@v4
         env:
           UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
@@ -111,15 +108,15 @@ jobs:
       - name: Measure Build Folder Size
         run: |
           echo "Build folder size:"
-          du -sh build/${{ matrix.targetPlatform }} || echo "Build folder not found."
+          du -sh build/WebGL || echo "Build folder not found."
         
 
       # Upload Build
-      - name: Upload the WebGL Build
+      - name: Upload Build
         uses: actions/upload-artifact@v4
         with:
-          name: Build ${{ vars.PROJECT_NAME }}-${{ matrix.targetPlatform }}-${{ github.run_id }}
-          path: build/${{ matrix.targetPlatform }}
+          name: Build ${{ vars.PROJECT_NAME }}-WebGL-${{ github.run_id }}
+          path: build/WebGL
           if-no-files-found: "warn"
 
       # Deploy to GH
@@ -127,7 +124,7 @@ jobs:
         uses: JamesIves/github-pages-deploy-action@4.1.3
         with:
           branch: gh-pages
-          folder: build/${{ matrix.targetPlatform }}
+          folder: build/WebGL
           target-folder: .
 
       - name: Calculate Build Duration
@@ -155,11 +152,11 @@ jobs:
         id: set-vars
         run: |
           if [ "${{ job.status }}" == "success" ]; then
-            echo "STATUS=✅ La build ${{ matrix.targetPlatform }} para la rama **${{ github.ref_name }}** se ha completado con éxito." >> $GITHUB_ENV
+            echo "STATUS=✅ La build WebGL para la rama **${{ github.ref_name }}** se ha completado con éxito." >> $GITHUB_ENV
             echo "COLOR=3066993" >> $GITHUB_ENV
             echo "THUMBNAIL_URL=https://e7.pngegg.com/pngimages/223/663/png-clipart-green-check-illustration-check-mark-checkbox-yes-miscellaneous-angle.png" >> $GITHUB_ENV
           else
-            echo "STATUS=❌ La build ${{ matrix.targetPlatform }} para la rama **${{ github.ref_name }}** ha fallado." >> $GITHUB_ENV
+            echo "STATUS=❌ La build WebGL para la rama **${{ github.ref_name }}** ha fallado." >> $GITHUB_ENV
             echo "COLOR=15158332" >> $GITHUB_ENV
             echo "THUMBNAIL_URL=https://e1.pngegg.com/pngimages/720/726/png-clipart-emoji-sticker-x-icon.png" >> $GITHUB_ENV
           fi
@@ -183,13 +180,16 @@ jobs:
                   "color": "${{ env.COLOR }}",
                   "fields": [
                     { "name": "🌿 Rama ", "value": "${{ github.ref_name }}" },
-                    { "name": "🎮 Plataforma ", "value": "${{ matrix.targetPlatform }}" },
+                    { "name": "🎮 Plataforma ", "value": "WebGL" },
                     { "name": "🔗 Enlace ", "value": "[Ver WebGL](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ vars.PROJECT_NAME }})" },
                     { "name": "⏱️ Duración ", "value": "${{ env.formatted_duration }}" }
                   ],
                   "footer": { 
                     "text": "GitHub Actions - Discord Integration", 
                     "icon_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
+                  },
+                  "author": {
+                    "name": "${{ vars.PROJECT_NAME }}"
                   },
                   "thumbnail": {
                     "url": "${{ env.THUMBNAIL_URL }}"
@@ -213,7 +213,7 @@ jobs:
           if [ "$response_code" -ge 400 ]; then
             echo "Error: Discord API devolvió un código de estado $response_code ❌."
             echo '{"content": "Error al enviar el mensaje a Discord ❌. [Ver workflow](${{ env.LINK_ACTION }})"}' > payload.json
-            curl -s -H "Content-Type: application/json" -d @payload.json ${{ secrets.DISCORD_WEBHOOK_URL }}
+            curl -s -H "Content-Type: application/json" -d @payload.json ***
           else
             echo "Mensaje enviado con éxito ✅."
           fi
